Repository AstrideUG/DarkBedrock, pull requests merged in 2019-06, with the labels that each got.

#111 3.3.1
  Darkness/common/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/general/functions/Json.kt
  Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/countdowns/Countdown.kt
  Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/countdowns/EndGameCountdown.kt
  Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/countdowns/LobbyCountdown.kt
  Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/countdowns/PreGameCountdown.kt
  Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/countdowns/SaveTimeCountdown.kt
  Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/functions/CommandSender.kt
  Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/functions/events/Cancellable.kt
  Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/functions/events/Events.kt
  Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/team/utils/Teams.kt
  build.gradle
Labels: bug, size/L

#113 Added Any.toConfigMap()
  Darkness/common/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/general/configs/StaticConfig.kt
Labels: enhancement, size/S

#114 Changed version to 3.4.0
  build.gradle
Labels: enhancement, size/XS

#129 Improved title of the dependency example
  README.md
Labels: enhancement
